[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --prefix tradeline-voice-server"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "npm start --prefix tradeline-voice-server"
